name: build / push to ECR

# FIXME: everything is hardcoded. can't handle multiple lambdas
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      create_ecr_repos:
        type: boolean
        description: 'Create ECR repositories?'
        required: false
        default: false

# allow for github actions to talk to aws
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create ECR repository if it doesn't exist
        run: |
          if [ "${{ github.event.inputs.create_ecr_repos }}" = "true" ]; then
          aws ecr describe-repositories --repository-names lambda_1 || \
          aws ecr create-repository --repository-name lambda_1
          fi

      - name: Build image
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 421239144093.dkr.ecr.us-west-2.amazonaws.com
          docker build -t lambda_1 lambdas/lambda_1
          docker tag lambda_1:latest 421239144093.dkr.ecr.us-west-2.amazonaws.com/lambda_1:latest

      - name: Check if image digest is different
        id: check-digest
        run: |
          LOCAL_DIGEST=$(docker inspect -f '{{.Id}}' lambda_1:latest)
          REMOTE_DIGEST=$(aws ecr describe-images --repository-name lambda_1 --image-ids imageTag=latest --query 'imageDetails[*].imageDigest' --output text)
          if [ "$LOCAL_DIGEST" != "$REMOTE_DIGEST" ]; then
            echo "::set-output name=digest-differs::true"
          else
            echo "::set-output name=digest-differs::false"
          fi

      - name: Push
        if: steps.check-digest.outputs.digest-differs == 'true'
        run: |
          docker push 421239144093.dkr.ecr.us-west-2.amazonaws.com/lambda_1:latest